linters:
  rubocop:
    display_cop_names: true
fixers:
    enable: true
    # indicate where is the config file for stylelint
    config: './rubocop.yml'

files:
  ignore:
    - "bin/*"
    - "db/*"
    - "config/*"
    - "Guardfile"
    - "Rakefile"
    - "README.md"
    - "node_modules/**/*"